@host=http://localhost:3000

### Get All Likes
GET {{host}}/likes
Content-Type: application/json

### Get Certain Person's Likes
GET {{host}}/likes/1
Content-Type: application/json

### Create an Array of Likes for a Person
POST {{host}}/likes
Content-Type: application/json

{
    "id": 10,
    "likes": [2,4,6,8]
}

### Patch a Movie
PATCH {{host}}/likes/10
Content-Type: application/json

{
    "likes": [2,4,6,8]
}

### Delete a Movie
DELETE {{host}}/likes/null
Content-Type: application/json

### Get Matches of a Person
GET {{host}}/matches/1
Content-Type: application/json
