@host=http://localhost:3000

### Get All Likes
GET {{host}}/likes
Content-Type: application/json

### Get Certain Person's Likes
GET {{host}}/likes/1
Content-Type: application/json

### Create a Movie
POST {{host}}
Content-Type: application/json

{
    "title": "Title 7",
    "overview": "Overview 7",
    "poster_path": "Path 7",
    "popularity": 40,
    "tags": ["tags7"]
}

### Patch a Movie
PATCH {{host}}/613c88a2ddeee8a071f13af5
Content-Type: application/json

{
    "title": "Title Test Patch 7"
}

### Delete a Movie
DELETE {{host}}/613c849ce6070783a44b80b5
Content-Type: application/json
