name: Node.js CI

on:
    push:
        branches: [ main, staging ]
    pull_request:
        branches: [ main, staging ]

env:
    DATABASE_URI_TEST: ${{secrets.DATABASE_URI_TEST}}
    DATABASE_NAME_TEST: ${{secrets.DATABASE_NAME_TEST}}
    DATABASE_COLLECTION_TEST: ${{secrets.DATABASE_COLLECTION_TEST}}
    PORT: ${{secrets.PORT}}
    JWT_SECRET: ${{secrets.JWT_SECRET}}

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        -   name: Checkout repository code
            uses: actions/checkout@v2
        -   name: Use Node.js 14
            uses: actions/setup-node@v2
            with:
                node-version: 14.x
        -   name: Start MongoDB
            uses: supercharge/mongodb-github-action@1.2.0
            with:
                mongodb-version: 4.4
                mongodb-port: 27017
        -   name: Install dependencies
            run: npm ci
        -   run: npm run build --if-present
        -   name: Run testing
            run: npm test
        -   name: Upload coverage to Codecov
            uses: codecov/codecov-action@v1
